# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mshresth <mshresth@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/23 01:16:00 by mshresth          #+#    #+#              #
#    Updated: 2025/08/04 03:33:34 by mshresth         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
CC = cc
CFLAGS = -Wall -Wextra -Werror

SRC = ft_strlen.c ft_isalpha.c ft_memset.c ft_bzero.c ft_calloc.c ft_strdup.c \
      ft_toupper.c ft_tolower.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c \
      ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memcpy.c ft_memmove.c ft_memchr.c \
      ft_memcmp.c ft_strlcpy.c ft_strlcat.c ft_strnstr.c ft_atoi.c ft_substr.c \
	  ft_strjoin.c ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c \
	  ft_split.c ft_striteri.c ft_strmapi.c ft_strtrim.c ft_tolower.c ft_toupper.c \
	  ft_itoa.c 

OBJ = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	ar rcs $(NAME) $(OBJ)

%.o: %.c libft.h
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re